apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: superset-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: 10.10.10.10
        - name: REDIS_HOST
          value: redis
        - name: DB_NAME
          value: superset
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcloud/google-cloud-key.json
        - name: PYTHONPATH
          value: "${PYTHONPATH}:/home/superset/superset/"
        image: amancevice/superset:latest
        name: superset
        ports:
        - containerPort: 8088
        volumeMounts:
        - mountPath: /secrets/database
          name: database
          readOnly: true
        - mountPath: /secrets/gcloud
          name: gcloud
          readOnly: true
        - mountPath: /home/superset/superset
          name: superset-config
      volumes:
      - name: database
        secret:
          secretName: database
      - name: gcloud
        secret:
          secretName: gcloud
      - name: superset-config
        configMap:
          name: superset-config
